# Generated by Django 4.0.3 on 2023-03-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('text_slide', models.CharField(max_length=250, verbose_name='Text')),
                ('link_slide', models.CharField(max_length=50, verbose_name='Link')),
                ('slide_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image')),
            ],
        ),
    ]
