# Generated by Django 4.0.3 on 2023-03-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_home_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_slide',
            name='link_text',
            field=models.CharField(default='Link', max_length=50, verbose_name='Button'),
        ),
    ]
