# Generated by Django 4.0.3 on 2023-03-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_home_slide_link_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image')),
            ],
        ),
    ]
