# Generated by Django 4.0.3 on 2023-03-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0004_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='title',
            field=models.CharField(default='logo', max_length=50, verbose_name='Title'),
        ),
    ]
