# Generated by Django 4.0.3 on 2023-03-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0005_logo_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_articl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('mutetext', models.CharField(max_length=50, verbose_name='Mute')),
                ('full_text', models.TextField(verbose_name='Articl')),
                ('venue_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='About_slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('text_slide', models.CharField(max_length=250, verbose_name='Text')),
                ('link_text', models.CharField(default='Link', max_length=50, verbose_name='Button')),
                ('link_slide', models.CharField(max_length=50, verbose_name='Link')),
                ('slide_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image')),
            ],
        ),
    ]
