# Generated by Django 4.0.3 on 2023-03-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0007_title_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('text', models.CharField(max_length=250, verbose_name='Text')),
                ('phone_first', models.CharField(max_length=50, verbose_name='Link')),
                ('phone_second', models.CharField(max_length=50, verbose_name='Link')),
                ('link_fph', models.CharField(max_length=50, verbose_name='Link')),
                ('link_sph', models.CharField(max_length=50, verbose_name='Link')),
            ],
        ),
        migrations.CreateModel(
            name='Email_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('text', models.CharField(max_length=250, verbose_name='Text')),
                ('link_mail', models.CharField(max_length=50, verbose_name='Link')),
                ('email_name', models.CharField(max_length=50, verbose_name='Link')),
            ],
        ),
        migrations.CreateModel(
            name='Social_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('text', models.CharField(max_length=250, verbose_name='Text')),
                ('link_face', models.CharField(max_length=50, verbose_name='Link')),
                ('link_inst', models.CharField(max_length=50, verbose_name='Link')),
                ('link_twit', models.CharField(max_length=50, verbose_name='Link')),
                ('link_in', models.CharField(max_length=50, verbose_name='Link')),
            ],
        ),
    ]
