# Generated by Django 4.0.3 on 2023-03-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0008_call_us_email_us_social_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call_us',
            name='link_fph',
            field=models.CharField(max_length=50, verbose_name='Link_mobile'),
        ),
        migrations.AlterField(
            model_name='call_us',
            name='link_sph',
            field=models.CharField(max_length=50, verbose_name='Link_phone'),
        ),
        migrations.AlterField(
            model_name='call_us',
            name='phone_first',
            field=models.CharField(max_length=50, verbose_name='mobile'),
        ),
        migrations.AlterField(
            model_name='call_us',
            name='phone_second',
            field=models.CharField(max_length=50, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='email_us',
            name='email_name',
            field=models.CharField(max_length=50, verbose_name='email_name'),
        ),
        migrations.AlterField(
            model_name='email_us',
            name='link_mail',
            field=models.CharField(max_length=50, verbose_name='Link_mail'),
        ),
        migrations.AlterField(
            model_name='social_us',
            name='link_face',
            field=models.CharField(max_length=50, verbose_name='Link_face'),
        ),
        migrations.AlterField(
            model_name='social_us',
            name='link_in',
            field=models.CharField(max_length=50, verbose_name='Link_in'),
        ),
        migrations.AlterField(
            model_name='social_us',
            name='link_inst',
            field=models.CharField(max_length=50, verbose_name='Link_inst'),
        ),
        migrations.AlterField(
            model_name='social_us',
            name='link_twit',
            field=models.CharField(max_length=50, verbose_name='Link_twit'),
        ),
    ]
