# Generated by Django 4.0.3 on 2023-03-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0009_alter_call_us_link_fph_alter_call_us_link_sph_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Send us message', max_length=50, verbose_name='Title')),
                ('label_name', models.CharField(default='Your name', max_length=50, verbose_name='Title')),
                ('label_email', models.CharField(default='Email address', max_length=50, verbose_name='Title')),
                ('label_mobile', models.CharField(default='Mobile number', max_length=50, verbose_name='Title')),
                ('label_message', models.CharField(default='Message ', max_length=50, verbose_name='Title')),
                ('info', models.CharField(default='By submitting this form you agree to our terms and conditions.', max_length=250, verbose_name='Text')),
                ('label_btn', models.CharField(default='Send', max_length=50, verbose_name='Title')),
            ],
        ),
        migrations.AlterField(
            model_name='call_us',
            name='link_fph',
            field=models.CharField(default='#', max_length=50, verbose_name='Link_mobile'),
        ),
        migrations.AlterField(
            model_name='call_us',
            name='link_sph',
            field=models.CharField(default='#', max_length=50, verbose_name='Link_phone'),
        ),
        migrations.AlterField(
            model_name='email_us',
            name='link_mail',
            field=models.CharField(default='#', max_length=50, verbose_name='Link_mail'),
        ),
        migrations.AlterField(
            model_name='social_us',
            name='link_face',
            field=models.CharField(default='#', max_length=50, verbose_name='Link_face'),
        ),
        migrations.AlterField(
            model_name='social_us',
            name='link_in',
            field=models.CharField(default='#', max_length=50, verbose_name='Link_in'),
        ),
        migrations.AlterField(
            model_name='social_us',
            name='link_inst',
            field=models.CharField(default='#', max_length=50, verbose_name='Link_inst'),
        ),
        migrations.AlterField(
            model_name='social_us',
            name='link_twit',
            field=models.CharField(default='#', max_length=50, verbose_name='Link_twit'),
        ),
    ]
