# Generated by Django 4.0.3 on 2023-03-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0012_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Publication date'),
        ),
        migrations.AddField(
            model_name='product',
            name='facilities_fir',
            field=models.CharField(blank=True, default='fa-snowflake', max_length=50, verbose_name='facilities 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='facilities_fou',
            field=models.CharField(blank=True, default='fa-water-ladder', max_length=50, verbose_name='facilities 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='facilities_sec',
            field=models.CharField(blank=True, default='fa-car', max_length=50, verbose_name='facilities 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='facilities_th',
            field=models.CharField(blank=True, default='fa-elevator', max_length=50, verbose_name='facilities 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='full_text',
            field=models.TextField(default='full text', max_length=1000, verbose_name='Articl'),
        ),
        migrations.AddField(
            model_name='product',
            name='label_btn',
            field=models.CharField(default='Add to Wishlist', max_length=50, verbose_name='Button'),
        ),
    ]
