# Generated by Django 4.1.7 on 2023-04-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0017_alter_image_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
