# Generated by Django 4.1.7 on 2023-04-05 10:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0022_alter_image_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='facilities_fir',
        ),
        migrations.RemoveField(
            model_name='product',
            name='facilities_fou',
        ),
        migrations.RemoveField(
            model_name='product',
            name='facilities_sec',
        ),
        migrations.RemoveField(
            model_name='product',
            name='facilities_th',
        ),
        migrations.AddField(
            model_name='product',
            name='facilities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'fa-snowflake'), ('item_key2', 'fa-car'), ('item_key3', 'fa-elevator'), ('item_key4', 'fa-water-ladder')], default=None, max_length=50),
        ),
    ]
