# Generated by Django 4.1.7 on 2023-04-06 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0023_remove_product_facilities_fir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bath_rooms',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Bath room'),
        ),
        migrations.AddField(
            model_name='product',
            name='rooms',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Room'),
        ),
    ]
