# Generated by Django 4.1.7 on 2023-04-06 13:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0024_product_bath_rooms_product_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='facilities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Elevator'), ('item_key2', 'Air conditioner'), ('item_key3', 'Garage'), ('item_key4', 'Pool')], default=None, max_length=50),
        ),
    ]
