# Generated by Django 4.1.7 on 2023-04-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0025_alter_product_facilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
