# Generated by Django 4.1.7 on 2023-04-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0027_product_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='address',
            field=models.CharField(default='12345 Moscow, Arbat 1', max_length=350, verbose_name='Address'),
        ),
    ]
