# Generated by Django 4.1.7 on 2023-04-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0028_product_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='instagram',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='product',
            name='skype',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='product',
            name='whatsapp',
            field=models.URLField(default='#'),
        ),
    ]
