# Generated by Django 4.1.7 on 2023-04-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0029_product_instagram_product_skype_product_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='instagram',
            field=models.URLField(default='https://www.instagram.com/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='skype',
            field=models.URLField(default='skype:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='whatsapp',
            field=models.URLField(default='https://wa.me/'),
        ),
    ]
