# Generated by Django 4.1.7 on 2023-04-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0030_alter_product_instagram_alter_product_skype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='instagram',
            field=models.URLField(blank=True, default='#'),
        ),
        migrations.AlterField(
            model_name='product',
            name='skype',
            field=models.URLField(blank=True, default='#'),
        ),
        migrations.AlterField(
            model_name='product',
            name='whatsapp',
            field=models.URLField(blank=True, default='#'),
        ),
    ]
