# Generated by Django 4.1.7 on 2023-04-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0034_product_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=15)),
                ('phone', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
    ]
