# Generated by Django 4.1.7 on 2023-04-11 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0035_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
